name: Publish to MCP Registry

on:
  push:
    tags: ["v*"]  # Triggers on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run tests (if present)
        run: uv run pytest || echo "No tests configured yet"
        continue-on-error: true

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish

      - name: Update server.json version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          python -c "import json; data=json.load(open('server.json')); data['version']='$VERSION'; data['packages'][0]['version']='$VERSION'; json.dump(data, open('server.json','w'), indent=2)"

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher

      - name: Login to MCP Registry (DNS Auth)
        run: |
          # Write PEM from secret to disk
          echo "${{ secrets.MCP_PRIVATE_KEY }}" > key.pem
          # Convert PEM -> DER -> take last 32 bytes (Ed25519 seed) -> hex encode
          PRIVATE_KEY_HEX=$(openssl pkey -in key.pem -outform DER | tail -c 32 | xxd -p -u -c 9999)
          # Pass private key as hex (mcp-publisher expects hex, not a file path)
          ./mcp-publisher login dns --domain allstacks.com --private-key "$PRIVATE_KEY_HEX"

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish

